customers/urls.py
from django.urls import path

from .views import render_pdf_view, CustomerListView, customer_render_pdf_view

app_name = 'customers'

urlpatterns = [
    path('', CustomerListView.as_view(), name='customer-list-view'),
    path('test/', render_pdf_view, name='test-view'),
    path('pdf/<pk>/', customer_render_pdf_view, name='customer-pdf-view'),
]

pdf_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customers.urls', namespace='cusomers')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

customers/models.py
from django.db import models


class Customer(models.Model):
    name = models.CharField(max_length=200)
    logo = models.ImageField()
    description = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)

customers/views.py
import os

from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.template.loader import get_template
from django.views.generic import ListView
from xhtml2pdf import pisa

from .models import Customer


class CustomerListView(ListView):
    model = Customer
    template_name = 'main.html'


def fetch_resources(uri, rel):
    """
    Callback to allow pisa/reportlab to retrieve Images,Stylesheets, etc.
    `uri` is the href attribute from the html link element.
    `rel` gives a relative path, but it's not used here.
    """
    path = os.path.join(settings.MEDIA_ROOT, uri.replace(settings.MEDIA_URL, ""))
    path = path.replace('/media/media/', '/media/')
    return path


def customer_render_pdf_view(request, *args, **kwargs):
    pk = kwargs.get('pk')
    customer = get_object_or_404(Customer, pk=pk)

    template_path = 'pdf2.html'
    context = {'customer': customer}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # if download:
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # if displayed:
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(html, link_callback=fetch_resources, dest=response)  #
    # if error then show some funy view
    """
    pdf = pisa.pisaDocument(StringIO.StringIO(
        html.encode("UTF-8")), 
        result, 
        link_callback=fetch_resources,
        encoding="utf-8")
    """

    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response


def render_pdf_view(request):
    template_path = 'pdf1.html'
    context = {'myvar': 'this is your template context'}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # if download:
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # if displayed:
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
        html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>PDFs | {% block title %}{% endblock title %}</title>
{#    <style>#}
{#        @font-face {#}
{#            font-family: Verdana;#}
{#            src: url(verdana.ttf);#}
{#        }#}
{##}
{#        html {#}
{#            font-family: Verdana;#}
{#            font-size: 11pt;#}
{#        }#}
{#    </style>#}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
<div class="container">
    {% block content %}
    {% endblock content %}
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Page Title</title>
  <link rel="stylesheet" href="style.css">
{#  <style>#}
{#    @font-face {#}
{#    font-family: Verdana;#}
{#    src: url(verdana.ttf);#}
{#    }#}
{##}
{#    html {#}
{#    font-family: Verdana;#}
{#    font-size: 11pt;#}
{#    }#}
{##}
{#    /*Обычный шрифт*/#}
{#    @font-face {#}
{#    font-family: Verdana;#}
{#    src: url(opens___.ttf);#}
{#    }#}
{##}
{#    /*Жирный шрифт*/#}
{#    @font-face {#}
{#    font-family: Verdana;#}
{#    src: url(verdana_bold.ttf);#}
{#    font-weight: bold;#}
{#    }#}
{#</style>#}

</head>
<body>
  <header class="header">
    <h1 class="header__title">Привет<br>мир! (Hello, world!)</h1>
  </header>
  <article class="article article_whitebg article_first">
    <h2 class="black">Это моя первая<br>страница!</h2>
      <p style="font-family: Verdana;">This is русский текст."</p>
    <p class="black">Я научился писать <strong>HTML</strong>, а теперь я подключил свой первый стилевой файл и всё стало красивым :) Очень скоро я научусь делать такие же <b>красивые страницы></b>, а вы будете мне завидовать!</p>
  </article>
  <div>
  m, ,.n ./,
sfdnhtrhwsdrtthwwr
dfsbhjntdejntfgeymkety
sarfthwehtt4ewhttjhtj
789 01 23
  </div>
</body>
</html>

templates/main.html
{% extends 'base.html' %}

{% block title%}

{% endblock title%}

{% block content %}
    {% for customer in  object_list %}
        {{ customer }}
        <a href="{% url 'customers:customer-pdf-view' customer.pk %}"><button class="btn btn-primary">PDF</button></a>
        <br>
        <hr>
    {% endfor %}
{% endblock content %}

templates/pdf1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PDF test</title>
</head>
<body>
{{ myvar }}
</body>
</html>

templates/pdf2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>

<h1>{{ customer }}</h1>
<hr>
{{ customer.description|linebreaks }}
<br>
{{ customer.logo }}
<br>
{{ costomer.logo.url }}
<br>
{{ customer.logo.path }}

{#    <img src={{customer.logo.path}} height='200px'>#}

<img src="media/{{ customer.logo }}" height='200px'>
<hr>
Конец.
</body>
</html>